package com.generalbytes.batm.server.extensions.extra.fiscalization.cis.hr.apis_it.fin._2012.services.fiskalizacijaservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-01-17T01:49:24.160+01:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://www.apis-it.hr/fin/2012/services/FiskalizacijaService", name = "FiskalizacijaPortType")
@XmlSeeAlso({com.generalbytes.batm.server.extensions.extra.fiscalization.cis.org.w3._2000._09.xmldsig_.ObjectFactory.class, com.generalbytes.batm.server.extensions.extra.fiscalization.cis.hr.apis_it.fin._2012.types.f73.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FiskalizacijaPortType {

    @WebMethod(action = "http://e-porezna.porezna-uprava.hr/fiskalizacija/2012/services/FiskalizacijaService/prateciDokumenti")
    @WebResult(name = "PrateciDokumentiOdgovor", targetNamespace = "http://www.apis-it.hr/fin/2012/types/f73", partName = "response")
    public com.generalbytes.batm.server.extensions.extra.fiscalization.cis.hr.apis_it.fin._2012.types.f73.PrateciDokumentiOdgovor prateciDokumenti(

        @WebParam(partName = "request", name = "PrateciDokumentiZahtjev", targetNamespace = "http://www.apis-it.hr/fin/2012/types/f73")
            com.generalbytes.batm.server.extensions.extra.fiscalization.cis.hr.apis_it.fin._2012.types.f73.PrateciDokumentiZahtjev request
    );

    @WebMethod(action = "http://e-porezna.porezna-uprava.hr/fiskalizacija/2012/services/FiskalizacijaService/racuniPD")
    @WebResult(name = "RacunPDOdgovor", targetNamespace = "http://www.apis-it.hr/fin/2012/types/f73", partName = "response")
    public com.generalbytes.batm.server.extensions.extra.fiscalization.cis.hr.apis_it.fin._2012.types.f73.RacunPDOdgovor racuniPD(

        @WebParam(partName = "request", name = "RacunPDZahtjev", targetNamespace = "http://www.apis-it.hr/fin/2012/types/f73")
            com.generalbytes.batm.server.extensions.extra.fiscalization.cis.hr.apis_it.fin._2012.types.f73.RacunPDZahtjev request
    );

    @WebMethod(action = "http://e-porezna.porezna-uprava.hr/fiskalizacija/2012/services/FiskalizacijaService/racuni")
    @WebResult(name = "RacunOdgovor", targetNamespace = "http://www.apis-it.hr/fin/2012/types/f73", partName = "response")
    public com.generalbytes.batm.server.extensions.extra.fiscalization.cis.hr.apis_it.fin._2012.types.f73.RacunOdgovor racuni(

        @WebParam(partName = "request", name = "RacunZahtjev", targetNamespace = "http://www.apis-it.hr/fin/2012/types/f73")
            com.generalbytes.batm.server.extensions.extra.fiscalization.cis.hr.apis_it.fin._2012.types.f73.RacunZahtjev request
    );

    @WebMethod(action = "http://e-porezna.porezna-uprava.hr/fiskalizacija/2012/services/FiskalizacijaService/echo")
    @WebResult(name = "EchoResponse", targetNamespace = "http://www.apis-it.hr/fin/2012/types/f73", partName = "response")
    public String echo(

        @WebParam(partName = "request", name = "EchoRequest", targetNamespace = "http://www.apis-it.hr/fin/2012/types/f73")
        String request
    );
}
